name: Create GitHub Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      prerelease:
        required: true
        type: boolean
      draft:
        required: true
        type: boolean
      iffile:
        required: true
        type: boolean
    secrets:
      RELEASE_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download README artifact
      uses: actions/download-artifact@v4
      with:
        name: release-readme
        path: ./readme
        
    - name: Download MSIX artifact
      if: ${{ inputs.iffile == true }}
      uses: actions/download-artifact@v4
      with:
        name: msix-package
        path: ./packages
        
    - name: Create GitHub Release (with files)
      if: ${{ inputs.iffile == true }}
      uses: softprops/action-gh-release@v2
      with:
        files: ./packages/*.msix
        body_path: ./readme/CHANGELOG.md
        name: "RailGo Release v${{ inputs.version }}"
        tag_name: "v${{ inputs.version }}"
        prerelease: ${{ inputs.prerelease }}
        draft: ${{ inputs.draft }}
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    - name: Create GitHub Release (without files)
      if: ${{ inputs.iffile == false }}
      uses: softprops/action-gh-release@v2
      with:
        body_path: ./readme/CHANGELOG.md
        name: "RailGo Release v${{ inputs.version }}"
        tag_name: "v${{ inputs.version }}"
        prerelease: ${{ inputs.prerelease }}
        draft: ${{ inputs.draft }}
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
